# This is a basic workflow to help you get started with Actions

name: TestPROGPOE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # list contents or directory
      - name: List contents
        run: ls
      #compiles classes to test
      - name: compile classes
        working-directory: ./src
        run: javac -cp "../testresoureces/junit-platform-console-standalone-1.6.0.jar" ./ST10445830/ST10445830.java ./ST10445830/Login.java "../test/ST10445830/ST10445830Test.java"  ../test/ST10445830/TaskTest.java" 
      
      # lists contents of src to verify that classes compliled
      - name: List contents of src directory after compile
        working-directory: ./src/ST10445830
        run: ls


      #copy compiled classes to test directory
      - name: copy compiled classes to testresources directory
        working-directory: ./src/ST10445830
        run: cp -t "../../test/ST10445830" ST10445830.class Login.class Task.class

      #copy compiled tests
      - name: copy compiled Test classes to testresources directory
        working-directory: ./test/ST10445830
        run: cp -t "../../testresources/"  ST10445830.class Login.class Task.class

      # list contents or directory
      - name: List contents test package
        working-directory: ./test/ST10445830
        run: ls

      #run mainclass class tests and output report
      - name: run main class tests and create report
        working-directory: ./test
        run: |
         ls
         java -jar  "../testresoureces/junit-platform-console-standalone-1.6.0.jar" -cp "." --selsect-class ST10445830.ST10445830Test
          
      #run Task class tests and output report
      - name: run Task Class tests and create report
        working-directory: ./test
        run: |
         ls
         java -jar  "../testresoureces/junit-platform-console-standalone-1.6.0.jar" -cp "." --selsect-class ST10445830.TaskTest
